import type { ProconPhysicalInput, ProconProfile } from "../types";

export const allProconPhysicalInputs: ProconPhysicalInput[] = [
  "buttonA",
  "buttonB",
  "buttonX",
  "buttonY",
  "buttonL",
  "buttonR",
  "buttonZL",
  "buttonZR",
  "buttonMinus",
  "buttonPlus",
  "buttonHome",
  "buttonCapture",
  "buttonLeftStick",
  "buttonRightStick",
  "dpadUp",
  "dpadDown",
  "dpadLeft",
  "dpadRight",
  "leftStickUp",
  "leftStickDown",
  "leftStickLeft",
  "leftStickRight",
  "rightStickUp",
  "rightStickDown",
  "rightStickLeft",
  "rightStickRight",
];

export const proconChromeProfile: ProconProfile = {
  id: "nintendo-switch-pro-controller-chrome",
  name: "Nintendo Switch Pro Controller on Chrome",
  inputs: {
    buttonB: { kind: "button", index: 0 },
    buttonA: { kind: "button", index: 1 },
    buttonY: { kind: "button", index: 2 },
    buttonX: { kind: "button", index: 3 },
    buttonL: { kind: "button", index: 4 },
    buttonR: { kind: "button", index: 5 },
    buttonZL: { kind: "button", index: 6 },
    buttonZR: { kind: "button", index: 7 },
    buttonMinus: { kind: "button", index: 8 },
    buttonPlus: { kind: "button", index: 9 },
    buttonLeftStick: { kind: "button", index: 10 },
    buttonRightStick: { kind: "button", index: 11 },
    dpadUp: { kind: "button", index: 12 },
    dpadDown: { kind: "button", index: 13 },
    dpadLeft: { kind: "button", index: 14 },
    dpadRight: { kind: "button", index: 15 },
    buttonHome: { kind: "button", index: 16 },
    buttonCapture: { kind: "button", index: 17 },
    leftStickLeft: { kind: "axis", index: 0, direction: -1 },
    leftStickRight: { kind: "axis", index: 0, direction: 1 },
    leftStickUp: { kind: "axis", index: 1, direction: -1 },
    leftStickDown: { kind: "axis", index: 1, direction: 1 },
    rightStickLeft: { kind: "axis", index: 2, direction: -1 },
    rightStickRight: { kind: "axis", index: 2, direction: 1 },
    rightStickUp: { kind: "axis", index: 3, direction: -1 },
    rightStickDown: { kind: "axis", index: 3, direction: 1 },
  },
};
